#' Install/Load Essential libraries
#'
#' @noRd
#'

# pkgs_name = rownames(installed.packages())
# if("packagename" %in% pkgs_name)
#   install("packagename")
#
# if (!require(golem))
#   utils::install.packages("golem")
# if (!require(tidyverse))
#   utils::install.packages("tidyverse")
# if (!require(rlang))
#   utils::install.packages("rlang")
# if (!require(dplyr))
#   utils::install.packages("dplyr")
# if (!require(readxl))
#   utils::install.packages("readxl")
# if (!require(tibble))
#   utils::install.packages("tibble")
# if (!require(VIM))
#   utils::install.packages("VIM")
# if (!require(lme4))
#   utils::install.packages("lme4")
# if (!require(ggpubr))
#   utils::install.packages("ggpubr")
# if (!require(gridExtra))
#   utils::install.packages("gridExtra")
# if (!require(ggplot2))
#   utils::install.packages("ggplot2")
# if (!require(shiny))
#   utils::install.packages("shiny")
# if (!require(shinydashboard))
#   utils::install.packages("shinydashboard")
# if (!require(shinydisconnect))
#   utils::install.packages("shinydisconnect")
# if (!require(shinyjs))
#   utils::install.packages("shinyjs")
# if (!require(DT))
#   utils::install.packages("DT")
# if (!require(glue))
#   utils::install.packages("glue")
# if (!require(data.table))
#   utils::install.packages("data.table")
# if (!require(lmerTest))
#   utils::install.packages("lmerTest")
